-- CRIAR DB 
CREATE DATABASE BUYHOUSE;

-- DEFINIR DB COMO PADRÃO / UTILIZÁVEL 
USE BUYHOUSE;

CREATE TABLE IMOVEL(
  ID INT NOT NULL,
  `BUILD_NAME` CHAR (20) NOT NULL,
  `CHAR_BIULD` CHAR (200) NOT NULL,
  `NUMBER_ROOMS` INT NOT NULL,
  `VALUE_G` FLOAT NOT NULL,
   PRIMARY KEY IMOVEL_ID (ID)
   );
   
   INSERT INTO IMOVEL (ID, BUILD_NAME, CHAR_BIULD, NUMBER_ROOMS, VALUE_G)
   VALUES (1, 'BIG HOUSE', 'BIG', 5, 350000),
          (2, 'SMALL HOUSE', 'SMALL', 1, 200000),
		  (3, 'GREEN HOUSE', 'GREEN', 2, 220000),
          (4, 'COUNTRY HOUSE', 'COUNTRY', 3, 550000),
		  (5, '2 STEPS HOUSE', 'LARGE 2 STEPS', 5, 280000),
          (6, '3 STEPS HOUSE', 'LARGE 3 STEPS', 7, 380000),
          (7, 'LARGER HOUSE', 'EXTRA LARGE', 9, 580000),
          (8, 'FLOREST HOUSE', 'THE FLOREST', 4, 590000), 
          (9, 'PINK HOUSE', 'PINK' , 2, 254000), 
          (10, 'GREY HOUSE', 'GREY', 3, 380000);
       
SELECT * 
FROM IMOVEL
WHERE NUMBER_ROOMS > 2;

SELECT *
FROM IMOVEL
WHERE VALUE_G > 250000;



